integratedgradients:
  baselines: 0
  n_steps: 20

gradientshap:
  baselines: 0

deeplift:
  eps: 0.000000001
  baselines: 0

saliency: {}

occlusion:
  sliding_window_shapes: 1
  baselines: 0

featureablation: {}

lime:
  n_samples: 100

kernelshap:
  baselines: 0
  n_samples: 100
