# Faithfulness

faithfulnesscorrelation:
  nr_runs: 100
  subset_size: 3136
  similarity_func: 'pearson'
  perturb_effect: 'minus'
  perturbation: 'replace'

faithfulnessestimate:
  features_in_step: 3136
  similarity_func: 'pearson'
  perturb_effect: 'minus'
  perturbation: 'replace'

monotonicitycorrelation:
  features_in_step: 3136
  similarity_func: 'spearman'
  perturb_effect: 'variance'
  perturbation: 'replace'

# pixelflipping:
#   features_in_step: 224
#   perturb_baseline: "black"

regionperturbation:
  regions_evaluation: 3136
  perturbation: 'replace'
  perturb_effect: 'minus'

insertion:
  pixel_batch_size: 3136 
  sigma: 120.0
  kernel_size: 39
  perturbation: 'replace'
  preservation: 'target'

deletion:
  pixel_batch_size: 224
  perturbation: 'replace'
  preservation: 'target'

negative:
  pixel_batch_size: 3136
  perturbation: 'replace'
  preservation: 'target'

positive:
  pixel_batch_size: 3136
  perturbation: 'replace'
  preservation: 'target'

irof:
  preservation: 'ratio'
  perturbation: 'replace'
  pixel_batch_size: 3136


infidelity:
  nr_runs: 100
  perturb_effect: 'minus'
  perturbation: 'replace'
  similarity_func: 'pearson'

# road:
#   noise: 0.1
#   percentages_max: 100

# sufficiency:
#   threshold: 0.6

# # Robustness

# locallipschitzestimate:
#   nr_samples: 5
#   perturb_std: 0.00002 
#   perturb_mean: 0.0

# maxsensitivity:
#   nr_samples: 10
#   lower_bound: 0.2

# continuity:
#   patch_size: 56
#   nr_steps: 20
#   perturb_baseline: "uniform"

# relativeinputstability:
#   nr_samples: 10

# relativeoutputstability:
#   nr_samples: 10

# relativerepresentationstability:
#   nr_samples: 10

# # Complexity

# sparseness: {}

# complexity: {}

# effectivecomplexity:
#   eps: 0.01